### ISSUE TITLE
Is there a way to return a view instead of an Image as the placeholder

### ISSUE THREAD

**Issue by yixe** [cmtrounce/SwURL#13]
To add something like a progression animation circle as a placeholder

**Comment by JonasDeichelmann** [comment]
@cmtrounce I would also be interested in a solution for that. I think your Package is nice to use.

**Comment by cmtrounce** [comment]
I’ll look into this

**Comment by JonasDeichelmann** [comment]
@cmtrounce 
Did you look at this ticket?

**Comment by cmtrounce** [comment]
Hi @JonasDeichelmann , Yes. I have to change a little bit of the logic under the hood, and observe the progress, so it shouldn't be too much work.

**Comment by cmtrounce** [comment]
@yixe , @JonasDeichelmann , do you have slack accounts?

**Comment by JonasDeichelmann** [comment]
@cmtrounce Yes, I do have a Slack account. But on which Workspace?

**Comment by cmtrounce** [comment]
> @cmtrounce Yes, I do have a Slack account. But on which Workspace?

@JonasDeichelmann ios-developers

**Comment by JonasDeichelmann** [comment]
@cmtrounce What Slack Channel is that?
I guess I need an invitation.

**Comment by cmtrounce** [comment]
https://ios-developers.io/ 
Try this! @JonasDeichelmann

**Comment by cmtrounce** [comment]
I'm laying the groundwork now to get this feature going. stay tuned.

**Comment by cmtrounce** [comment]
@JonasDeichelmann  / @yixe 
0.3.0 (just been released) is the first step towards this. I had to change the underlying views to support `AnyView`. 
Now that's done, it's opened up the flexibility to add support for providing any View as a placeholder. 

I'll provide a closure format `(percentageComplete) -> some View` so you can return whatever you like , based on progress.

**Comment by cmtrounce** [comment]
@yixe do you have a way I can get in contact with you? twitter? slack?

**Comment by cmtrounce** [comment]
@yixe , on the develop branch I've added a function called progress where you can return a view which will display whilst content is loading

**Comment by cmtrounce** [comment]
This has been resolved in release 0.4.0
