### ISSUE TITLE
Result url not present in handleDownload

### ISSUE THREAD

**Issue by a-shatou** [cmtrounce/SwURL#14]
Here is the view: 

`var body: some View {
        VStack(alignment: .center, spacing: 16, content: {
            Spacer()
            HStack {
                Spacer()
                RemoteImageView(url: contact.iconUrl(),
                                placeholderImage: Image.init("ministry_logo"),
                                transition: .custom(transition: .opacity,
                                                    animation: .easeOut(duration: 0.5))).frame(width: 100, height: 100, alignment: .center)
                Spacer()
            }
        })
    }`

When enabling logging, this is the message I get: "Result url not present in handleDownload" which obviously is not obvious at all. What I am missing here?

**Comment by cmtrounce** [comment]
Hey @a-shatou , do you have a slack account?

**Comment by cmtrounce** [comment]
The 'Result url not present in handleDownload' is just indicating that there is progress when downloading / the image hasn't finished downloading. next version I'll improve logging :D

**Comment by a-shatou** [comment]
> Hey @a-shatou , do you have a slack account? 

Nope.

**Comment by a-shatou** [comment]
> The 'Result url not present in handleDownload' is just indicating that there is progress when downloading / the image hasn't finished downloading. next version I'll improve logging :D 

Ok, got it 🙂

**Comment by cmtrounce** [comment]
@a-shatou  if you check out the `develop` branch, it's got a few improvements, and that's where I'll be testing / improving the logging at this evening. feel free to take a look. I've changed the syntax a little bit, to allow the image to be a little more customisable.

**Comment by cmtrounce** [comment]
I've just made a push, give it a go.

**Comment by cmtrounce** [comment]
@a-shatou are you happy for me to close this issue? I think I've answered your question

**Comment by cmtrounce** [comment]
Closing, 0.3.0 includes improved debugging.
