### ISSUE TITLE
RemoteImageView Bug in 0.4.1

### ISSUE THREAD

**Issue by ddunne6** [cmtrounce/SwURL#18]
When attempting to use RemoteImageView with 0.4.1 I got the following error, “Static method 'buildBlock' requires that 'SwURL' conform to 'View'”. When I changed to 0.4.0 the error message went away.

**Comment by cmtrounce** [comment]
Hi @ddunne6 , can I please see a code snippet where the error happened please?

**Comment by sgtpeppr** [comment]
Having the same error. Just copied the sample code into a new SwiftUI file and updated references to landmark. Problem does not exist in 0.4.0.
![image](https://user-images.githubusercontent.com/7807860/132264398-38dedb6b-f104-4f0f-a18d-e298fcb75ad4.png)

**Comment by ariobarxan** [comment]
RemoteImageView not working at all 
Error:
Static method 'buildBlock' requires that 'SwURLImageView' conform to 'View'

**Comment by mennyaL** [comment]
Same

**Comment by cmtrounce** [comment]
Hi all, I've made reversions in 0.4.2 so you should no longer be experiencing this issue.

**Comment by cmtrounce** [comment]
Please get the latest version of the SDK, there comes improvements, optimisations and improved documentation
