### ISSUE TITLE
Image not loading on beta 5

### ISSUE THREAD

**Issue by benclanet** [cmtrounce/SwURL#4]
Hi,

here's pretty much how I use your lib: https://gist.github.com/benclanet/a5a02e613c344d0af888859c42a16001

What happens is a blank view. When I activate the logs, I do see `Image successfully retrieved from url:`... 

Any idea what could be wrong?

Thank you!

**Comment by cmtrounce** [comment]
Hi @ben! 

It very likely that it’s due to the current version supporting up to beta 4 only (beta 5 support will commence shortly) 

I will see if I can reproduce your problem some time during this week, but the fix will likely come out with the Beta 5 support

**Comment by cmtrounce** [comment]
Update @benclanet , this will be resolved when I add beta 6 support.

**Comment by cmtrounce** [comment]
Hi @benclanet , I have released a version which has beta 5 support, can you please try it?
