### ISSUE TITLE
Image not displaying correctly inside a Navigation item

### ISSUE THREAD

**Issue by peter-w-williams** [cmtrounce/SwURL#8]
If you use the image inside a navigation item it displays as a blue rectangle. The following modifier is required on the image to prevent this issue .renderingMode(.original),

An example is shown below

 TransitioningImage.init(placeholder: placeholderImage?.resizable().renderingMode(.original),
                                finalImage: remoteImage.load(url: url).image?.resizable().renderingMode(.original),
                                transitionType: transitionType)
    }

**Comment by cmtrounce** [comment]
@peter-w-williams thanks for this, I'll see what can be done to resolve this.

**Comment by cmtrounce** [comment]
Hi @peter-w-williams , version 0.2.2 allows support for providing the desired image rendering mode. Please take a look at the updated README
