### ISSUE TITLE
Crash in RemoteImage.swift

### ISSUE THREAD

**Issue by Exey** [cmtrounce/SwURL#9]
I've got around 100 crashed last week on:
```Fatal error: Attempted to read an unowned reference but object 0x281a63d90 was already deallocated2019-09-09 12:53:13.434243+0300[14534:1447031] Fatal error: Attempted to read an unowned reference but object```
on 34 String in RemoteImage.string
![crash](https://i.postimg.cc/0QzYThfD/Screenshot-2019-09-09-at-12-55-39.png)

**Comment by cmtrounce** [comment]
Heya! I'll check this out! A lot has changed since beta 5/6 so it's likely related.

**Comment by cmtrounce** [comment]
Hi, @Exey a new version is available on master. Can you please verify that the crash is no longer occurring?
